name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'   # 每天凌晨3点自动执行（可根据需要调整时间）
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/上游作者/上游仓库名.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into local main
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
